### PR TITLE
Compute plan: support composite/aggregate

### LINKED ISSUE #31: [BUG] queryComputePlans returns null instead of [] when there are no computePlans
**Describe the bug**

All "queryAssets" functions return an empty list when there are no assets available. `queryComputePlans` on the other hand returns `null`. 

**To Reproduce**

* call queryComputePlans on a brand new instance of the platform

**Expected behavior**

Expected return value: `[]`

Actual return value: `null`

### LINKED ISSUE #36: [BUG] createComputePlan and queryComputePlan(s) have different outputs
**Describe the bug**
Use `createComputePlan` and you'll get an `outputComputePlan` while the `queryComputePlan` and `queryComputePlans` method return `outputComputePlanDetails`

This means that the former one doesn't include the `algoKey` and `objectiveKey` while the latter ones use `traintuples`/`testtuples` instead of `traintupleKeys`/`testtupleKeys`.

**Expected behavior**

They should return the same data in the same format.

This common format could be a mix of the two structs with the attributes:
* `computePlanID`
* `algoKey`
* `objectiveKey`
* `traintupleKeys`
* `testtupleKeys`

I offer to use traintupleKeys and testtupleKeys because we don't include the full traintuples and testtuples in the compute plan.

Also, when the testtupleKeys is empty, an empty list should be returned (instead of `null`)

### PR DESCRIPTION
**Pull request by AurelienGasser**
Companion PR: [substra-backend](https://github.com/SubstraFoundation/substra-backend/pull/57)

This updates the compute plan structures to support composite/aggregate.

Fixes https://github.com/SubstraFoundation/substra-chaincode/issues/31

Fixes https://github.com/SubstraFoundation/substra-chaincode/issues/36

### CODE REVIEW

File: chaincode/compute_plan_dag.go [hunk 1]
```diff
@@ -67,7 +71,7 @@ func (dag *ComputeDAG) sort() error {
 		if ready {
 			final = append(final, current[i])
 			if _, ok := IDPresents[current[i].ID]; ok {
-				return fmt.Errorf("compute plan error, ID use twice: %s", current[i].ID)
+				return fmt.Errorf("Compute plan error: Duplicate training task ID: %s", current[i].ID)
```
Comment (thibaultrobert) [inline chaincode/compute_plan_dag.go]: The error message should not start with a capital letter since it can be composed later on with another.

File: chaincode/ledger.go [hunk 2]
```diff
@@ -88,57 +88,72 @@ type AggregateAlgo struct {
...
 	InHeadModel   string                      `json:"inHeadModel"`
 	InTrunkModel  string                      `json:"inTrunkModel"`
-	Log           string                      `json:"log"`
-	ObjectiveKey  string                      `json:"objectiveKey"`
 	OutHeadModel  CompositeTraintupleOutModel `json:"outHeadModel"`
 	OutTrunkModel CompositeTraintupleOutModel `json:"outTrunkModel"`
 	Perf          float32                     `json:"perf"`
-	Rank          int                         `json:"rank"`
-	Status        string                      `json:"status"`
-	Tag           string                      `json:"tag"`
```
Comment (thibaultrobert) [inline chaincode/ledger.go:125]: I don't mind resorting struct element but I'm not a sure what's the logic behind this order (also an alphabetic order was ok for me)

**Review by thibaultrobert — DISMISSED** [review]

File: chaincode/compute_plan_dag.go (hunk 1 above)
Comment (AurelienGasser) [reply chaincode/compute_plan_dag.go]: I see @inalgnu already fixed it! Under what scenario would we compose this error with others?

File: chaincode/main.go [hunk 3]
```diff
@@ -170,6 +170,12 @@ func (t *SubstraChaincode) Invoke(stub shim.ChaincodeStubInterface) peer.Respons
 	if err != nil {
 		return formatErrorResponse(err)
 	}
+	// Send event if there is any. It's done in one batch since we can only send
+	// one event per call
+	err = db.SendTuplesEvent()
+	if err != nil {
+		return formatErrorResponse(fmt.Errorf("could not send event for unknown reason"))
```
Comment (AurelienGasser) [inline chaincode/main.go]: Is there a reason not to add the error returned by `SendTuplesEvent` as part of this error, instead of saying the error is unknown?

File: chaincode/traintuple.go [hunk 4]
```diff
@@ -377,22 +363,12 @@ func logFailTrain(db LedgerDB, args []string) (outputTraintuple outputTraintuple
...
-	event := TuplesEvent{}
-	err = UpdateTesttupleChildren(db, inp.Key, traintuple.Status, &event)
-	if err != nil {
-		return
-	}
-
-	err = UpdateTraintupleChildren(db, inp.Key, traintuple.Status, &event)
-	if err != nil {
-		return
-	}
```
Comment (AurelienGasser) [inline chaincode/traintuple.go:375]: These err blocks have been removed, is it intentional?

Comment (AurelienGasser) [reply chaincode/traintuple.go:375]: nevermind, I just can't read right :D

File: chaincode/compute_plan_dag.go (hunk 1 above)
Comment (inelgnu) [reply chaincode/compute_plan_dag.go]: @AurelienGasser https://github.com/golang/go/wiki/CodeReviewComments#error-strings

File: chaincode/ledger_db.go [hunk 5]
```diff
@@ -383,3 +384,73 @@ func (db *LedgerDB) GetNode(key string) (Node, error) {
...
 	return node, nil
 }
+
+// ----------------------------------------------
+// High-level functions for events
+// ----------------------------------------------
+
+// SendTuplesEvent sends an event with updated tuples if there is any
+// Only one event can be sent per transaction
+func (db *LedgerDB) SendTuplesEvent() error {
```
Comment (AurelienGasser) [inline chaincode/ledger_db.go:394]: I think you forgot to remove the original method from `utils.go`

File: chaincode/ledger.go (hunk 2 above)
Comment (AurelienGasser) [reply chaincode/ledger.go:125]: I sorted it this way so that the common members between Traintuple, CompositeTraintuple and AggregateTuple are all at the top (and hopefully can eventually be removed altogether, in favor of structure composition where `GenericTuple` would be included as part of each sub-structure? to be discussed :p)

I can revert to the original sort, if you prefer?

File: chaincode/compute_plan_dag.go (hunk 1 above)
Comment (AurelienGasser) [reply chaincode/compute_plan_dag.go]: Thank you! 

Following that logic, what would you think of removing the "Compute plan error: " part of the error string?

Comment (AurelienGasser) [reply chaincode/compute_plan_dag.go]: Talked with @thibaultrobert : let's leave it as it is now.

File: chaincode/ledger.go (hunk 2 above)
Comment (AurelienGasser) [reply chaincode/ledger.go:125]: discussed with @thibaultrobert : no strong opinion, let's leave it as it is now.

File: chaincode/ledger_db.go (hunk 5 above)
Comment (AurelienGasser) [reply chaincode/ledger_db.go:394]: confirmed with @thibaultrobert this needs fixing

File: chaincode/main.go (hunk 3 above)
Comment (AurelienGasser) [reply chaincode/main.go]: confirmed with @thibaultrobert this needs fixing

File: chaincode/ledger_db.go (hunk 5 above)
Comment (AurelienGasser) [reply chaincode/ledger_db.go:394]: fixed: https://github.com/SubstraFoundation/substra-chaincode/pull/41/commits/d06ce2fd5387ea3c48400161227abd2f6c1be4d2

File: chaincode/main.go (hunk 3 above)
Comment (AurelienGasser) [reply chaincode/main.go]: fixed: https://github.com/SubstraFoundation/substra-chaincode/pull/41/commits/53ccf231c878e305f5aef1e17ca09dc5671690d8

**Review by inelgnu — DISMISSED** [review]

**Review by thibaultrobert — APPROVED** [review]
