### PR TITLE
Correct errors

### LINKED ISSUE #77: [BUG] Chaincode returns 500 error instead of 400 in some cases
**Describe the bug**
The chaincode responds in some cases a 500 error instead of a 400 error. For traceability and debugging it should be fixed: 500 errors are server errors and 400 errors are user errors.
 
**Investigation**

This is at least true for the following error:
```go
            return Permissions{}, fmt.Errorf("invalid permission input values")
```

We should go through all the errors returned by the chaincode and ensured they have the proper status code.

### PR DESCRIPTION
**Pull request by thibaultrobert**
Fixes #77

### CODE REVIEW

File: chaincode/compute_plan.go [hunk 1]
```diff
@@ -31,7 +30,7 @@ func (inpTraintuple *inputTraintuple) Fill(inpCP inputComputePlanTraintuple, tra
 	for _, InModelID := range inpCP.InModelsIDs {
 		inModelKey, ok := traintupleKeysByID[InModelID]
 		if !ok {
-			return fmt.Errorf("model ID %s not found", InModelID)
+			return errors.BadRequest("model ID %s not found", InModelID)
```
Comment (inelgnu) [inline chaincode/compute_plan.go:33]: shouldn't this be a NotFound error?

File: chaincode/compute_plan_dag.go [hunk 2]
```diff
@@ -75,7 +75,7 @@ func (dag *ComputeDAG) sort() error {
 			current[i].Depth = depth
 			final = append(final, current[i])
 			if _, ok := IDPresents[current[i].ID]; ok {
-				return fmt.Errorf("compute plan error: Duplicate training task ID: %s", current[i].ID)
+				return errors.Internal("compute plan error: Duplicate training task ID: %s", current[i].ID)
```
Comment (inelgnu) [inline chaincode/compute_plan_dag.go]: This error seems to be a conflict, no?

File: chaincode/compute_plan.go (hunk 1 above)
Comment (thibaultrobert) [reply chaincode/compute_plan.go:33]: The ID are found in the input, so if it's missing it's due to the arguments so a BadRequest was more logical what do you think?

Comment (inelgnu) [reply chaincode/compute_plan.go:33]: indeed

File: chaincode/compute_plan_dag.go (hunk 2 above)
Comment (thibaultrobert) [reply chaincode/compute_plan_dag.go]: Yes it's a conflict problem... Will update it

Comment (thibaultrobert) [reply chaincode/compute_plan_dag.go]: Done

File: chaincode/compute_plan_dag.go [hunk 3]
```diff
@@ -75,7 +75,7 @@ func (dag *ComputeDAG) sort() error {
 			current[i].Depth = depth
 			final = append(final, current[i])
 			if _, ok := IDPresents[current[i].ID]; ok {
-				return fmt.Errorf("compute plan error: Duplicate training task ID: %s", current[i].ID)
+				return errors.Conflict("compute plan error: Duplicate training task ID: %s", current[i].ID)
```
Comment (samlesu) [inline chaincode/compute_plan_dag.go]: This is a BadRequest? The request is invalid due to duplicate ids. What do you think?

File: chaincode/compute_plan_dag.go [hunk 4]
```diff
@@ -90,7 +90,7 @@ func (dag *ComputeDAG) sort() error {
 			for _, c := range current {
 				errorIDs = append(errorIDs, c.ID)
 			}
-			return fmt.Errorf("compute plan error: Cyclic or missing dependency among inModels IDs: %v", errorIDs)
+			return errors.Internal("compute plan error: Cyclic or missing dependency among inModels IDs: %v", errorIDs)
```
Comment (samlesu) [inline chaincode/compute_plan_dag.go]: Could be a BadRequest as well: we don't support cyclic graph.

File: chaincode/compute_plan_dag.go (hunk 3 above)
Comment (thibaultrobert) [reply chaincode/compute_plan_dag.go]: I would say it's debatable here because its still a conflict but I think BadRequest is more coherent with the rest so let's change it.

Comment (thibaultrobert) [reply chaincode/compute_plan_dag.go]: Done

File: chaincode/compute_plan_dag.go (hunk 4 above)
Comment (thibaultrobert) [reply chaincode/compute_plan_dag.go]: Done

**Review by samlesu — APPROVED** [review]
LGTM

**Review by inelgnu — APPROVED** [review]
